"""
i18n_tools.py — Open Accountant · i18n utilities via Babel.

Usage:
  python3 i18n_tools.py extract    # JSON → .po files
  python3 i18n_tools.py compile    # .po → .mo files (gettext binary)
  python3 i18n_tools.py stats      # coverage report
"""

import json
import sys
from pathlib import Path
from datetime import datetime

import app_version

BASE = Path(__file__).parent
LOCALES_JS = BASE / "static" / "locales"  # JSON source of truth
LOCALES_PO = BASE / "locales"  # .po / .mo output
LANGUAGES = ["en", "es"]

PO_HEADER = """\
# Open Accountant — {lang} translations
# Generated by i18n_tools.py on {date}
# msgid = English key, msgstr = translation
#
msgid ""
msgstr ""
"Project-Id-Version: Open Accountant {version}\\n"
"Language: {lang}\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"

"""


def _load_json(lang: str) -> dict:
    path = LOCALES_JS / f"{lang}.json"
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _po_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _write_po(lang: str, translations: dict, en_keys: dict):
    po_dir = LOCALES_PO / lang / "LC_MESSAGES"
    po_dir.mkdir(parents=True, exist_ok=True)
    po_path = po_dir / "messages.po"
    lines = [
        PO_HEADER.format(
            lang=lang,
            date=datetime.now().strftime("%Y-%m-%d"),
            version=app_version.numeric_version(),
        )
    ]
    for key, en_val in en_keys.items():
        if key.startswith("_"):
            continue
        trans = translations.get(key, "")
        lines.append(f'msgid "{_po_escape(key)}"\n')
        lines.append(f'msgstr "{_po_escape(trans)}"\n\n')
    with open(po_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"  → {po_path}  ({len(en_keys)} strings)")


def cmd_extract():
    """JSON → .po files."""
    print("Extracting translations to .po files…")
    en = _load_json("en")
    for lang in LANGUAGES:
        data = _load_json(lang)
        _write_po(lang, data, en)
    print("Done.")


def cmd_compile():
    """Compile .po → .mo using Babel/msgfmt."""
    try:
        from babel.messages.mofile import write_mo
        from babel.messages.pofile import read_po
    except ImportError:
        print(
            "ERROR: babel not installed. Run: pip install babel --break-system-packages"
        )
        sys.exit(1)

    print("Compiling .po → .mo…")
    for lang in LANGUAGES:
        po_path = LOCALES_PO / lang / "LC_MESSAGES" / "messages.po"
        mo_path = po_path.with_suffix(".mo")
        if not po_path.exists():
            print(f"  SKIP {lang}: {po_path} not found (run extract first)")
            continue
        with open(po_path, "rb") as f:
            catalog = read_po(f, locale=lang)
        with open(mo_path, "wb") as f:
            write_mo(f, catalog)
        print(f"  → {mo_path}")
    print("Done.")


def cmd_stats():
    """Coverage report."""
    print("Translation coverage:")
    en = _load_json("en")
    keys = [k for k in en if not k.startswith("_")]
    for lang in LANGUAGES:
        data = _load_json(lang)
        missing = [k for k in keys if k not in data or not data[k]]
        pct = (len(keys) - len(missing)) / len(keys) * 100
        print(f"  {lang}: {len(keys) - len(missing)}/{len(keys)} ({pct:.0f}%)")
        if missing:
            for m in missing[:10]:
                print(f"    ✗ {m}")
            if len(missing) > 10:
                print(f"    … and {len(missing)-10} more")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "stats"
    {"extract": cmd_extract, "compile": cmd_compile, "stats": cmd_stats}.get(
        cmd, lambda: print(f"Unknown command: {cmd}. Use: extract | compile | stats")
    )()
