"""Compatibility facade for the split `services.projections` package.

This module preserves the historic import path and the `date` monkeypatching
used by tests, while the implementation now lives under `services/projections/`.
"""

from datetime import date

from services.projections import (
    _add_months,
    _aggregate,
    _build_slider_config,
    _compute_series_adjustments,
    _estimate_investment_model,
    _fill_by_regression,
    _financial_rows,
    _get_monthly_balances,
    _get_monthly_cashflow,
    _get_monthly_dividend_income,
    _get_monthly_investment_balances,
    _get_monthly_investment_contributions,
    _identify_dividend_accounts,
    _identify_investment_accounts,
    _indexed_linear_regression,
    _iqr_filter,
    _iqr_filter_samples,
    _linear_regression,
    _month_str,
    _month_to_index,
    _months_range,
    _normalize_investment_stat,
    _parse_month,
    _project_flow_from_settings,
    _project_investments,
    _resolve_investment_projection_inputs,
    _round_or_none,
    _safe_ratio,
    _series_start_month,
    _slider_step,
    _sparse_linear_regression,
    build_projections,
    create_series,
    delete_series,
    get_series,
    list_series,
    update_series,
)


def get_projections(
    conn,
    horizon: int,
    history_months: int,
    *,
    income_trend_mode: str = "linear",
    income_trend_min: float | None = None,
    income_trend_max: float | None = None,
    income_inflation_base: float | None = None,
    income_inflation_rate: float | None = None,
    expense_trend_mode: str = "linear",
    expense_trend_min: float | None = None,
    expense_trend_max: float | None = None,
    expense_inflation_base: float | None = None,
    expense_inflation_rate: float | None = None,
    investment_lookback_months: int | None = None,
    investment_include_current_month: bool = False,
    investment_stat: str = "mean",
    investment_exclude_outliers: bool = True,
    investment_outlier_k: float = 1.5,
    investment_interest_pct_override: float | None = None,
    investment_contribution_pct_override: float | None = None,
    investment_interest_override: float | None = None,
    investment_contribution_override: float | None = None,
) -> dict:
    return build_projections(
        conn,
        horizon,
        history_months,
        today=date.today(),
        income_trend_mode=income_trend_mode,
        income_trend_min=income_trend_min,
        income_trend_max=income_trend_max,
        income_inflation_base=income_inflation_base,
        income_inflation_rate=income_inflation_rate,
        expense_trend_mode=expense_trend_mode,
        expense_trend_min=expense_trend_min,
        expense_trend_max=expense_trend_max,
        expense_inflation_base=expense_inflation_base,
        expense_inflation_rate=expense_inflation_rate,
        investment_lookback_months=investment_lookback_months,
        investment_include_current_month=investment_include_current_month,
        investment_stat=investment_stat,
        investment_exclude_outliers=investment_exclude_outliers,
        investment_outlier_k=investment_outlier_k,
        investment_interest_pct_override=investment_interest_pct_override,
        investment_contribution_pct_override=investment_contribution_pct_override,
        investment_interest_override=investment_interest_override,
        investment_contribution_override=investment_contribution_override,
    )


__all__ = [
    "_add_months",
    "_aggregate",
    "_build_slider_config",
    "_compute_series_adjustments",
    "_estimate_investment_model",
    "_fill_by_regression",
    "_financial_rows",
    "_get_monthly_balances",
    "_get_monthly_cashflow",
    "_get_monthly_dividend_income",
    "_get_monthly_investment_balances",
    "_get_monthly_investment_contributions",
    "_identify_dividend_accounts",
    "_identify_investment_accounts",
    "_indexed_linear_regression",
    "_iqr_filter",
    "_iqr_filter_samples",
    "_linear_regression",
    "_month_str",
    "_month_to_index",
    "_months_range",
    "_normalize_investment_stat",
    "_parse_month",
    "_project_flow_from_settings",
    "_project_investments",
    "_resolve_investment_projection_inputs",
    "_round_or_none",
    "_safe_ratio",
    "_series_start_month",
    "_slider_step",
    "_sparse_linear_regression",
    "create_series",
    "delete_series",
    "get_projections",
    "get_series",
    "list_series",
    "update_series",
]
