"""Schema bootstrap and metadata helpers."""

from db.connection import get_db
from db.dialect import _prefixed_table_name

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS oacc_settings (
    section     TEXT NOT NULL,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (section, key)
);

CREATE TABLE IF NOT EXISTS oacc_types (
    id   INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS oacc_subtypes (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL,
    type_id INTEGER NOT NULL REFERENCES oacc_types(id) ON DELETE RESTRICT,
    UNIQUE(name, type_id)
);

CREATE TABLE IF NOT EXISTS oacc_accounts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    type_id         INTEGER NOT NULL REFERENCES oacc_types(id) ON DELETE RESTRICT,
    subtype_id      INTEGER REFERENCES oacc_subtypes(id) ON DELETE SET NULL,
    description     TEXT NOT NULL DEFAULT '',
    initial_balance DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    properties      TEXT NOT NULL DEFAULT '{}',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oacc_transactions (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debit_account     INTEGER NOT NULL REFERENCES oacc_accounts(id) ON DELETE RESTRICT,
    credit_account    INTEGER NOT NULL REFERENCES oacc_accounts(id) ON DELETE RESTRICT,
    amount            DOUBLE PRECISION NOT NULL CHECK(amount > 0),
    original_amount   DOUBLE PRECISION NOT NULL CHECK(original_amount > 0),
    original_currency TEXT NOT NULL DEFAULT 'ARS',
    fx_rate           DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK(fx_rate > 0),
    fx_source         TEXT,
    description       TEXT NOT NULL DEFAULT '',
    date              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oacc_tags (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    TEXT,
    name       TEXT NOT NULL,
    color      TEXT NOT NULL DEFAULT '#3B82F6',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oacc_transaction_tags (
    transaction_id INTEGER NOT NULL REFERENCES oacc_transactions(id) ON DELETE CASCADE,
    tag_id         INTEGER NOT NULL REFERENCES oacc_tags(id) ON DELETE CASCADE,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (transaction_id, tag_id)
);

CREATE TABLE IF NOT EXISTS oacc_user_preferences (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oacc_users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    is_admin      BOOLEAN NOT NULL DEFAULT FALSE,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oacc_auth_sessions (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES oacc_users(id) ON DELETE CASCADE,
    token_hash   TEXT NOT NULL UNIQUE,
    expires_at   TEXT NOT NULL,
    remember_me  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS oacc_projection_series (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    type           TEXT NOT NULL CHECK(type IN ('income', 'expense', 'investment', 'rescue')),
    start_date     DATE NOT NULL,
    months         INTEGER NOT NULL CHECK(months >= 1),
    period_months  INTEGER NOT NULL DEFAULT 1 CHECK(period_months >= 1),
    enabled        BOOLEAN NOT NULL DEFAULT TRUE,
    confirmed      BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_amount DOUBLE PRECISION NOT NULL CHECK(monthly_amount > 0),
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS oacc_idx_tx_debit ON oacc_transactions(debit_account);
CREATE INDEX IF NOT EXISTS oacc_idx_tx_credit ON oacc_transactions(credit_account);
CREATE INDEX IF NOT EXISTS oacc_idx_tx_date ON oacc_transactions(date);
CREATE INDEX IF NOT EXISTS oacc_idx_acc_type ON oacc_accounts(type_id);
CREATE INDEX IF NOT EXISTS oacc_idx_tags_name ON oacc_tags(LOWER(name));
CREATE UNIQUE INDEX IF NOT EXISTS oacc_idx_tags_name_unique ON oacc_tags(LOWER(name));
CREATE INDEX IF NOT EXISTS oacc_idx_transaction_tags_tag ON oacc_transaction_tags(tag_id);
CREATE UNIQUE INDEX IF NOT EXISTS oacc_idx_users_username_unique ON oacc_users(LOWER(username));
CREATE INDEX IF NOT EXISTS oacc_idx_auth_sessions_user_id ON oacc_auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS oacc_idx_auth_sessions_expires_at ON oacc_auth_sessions(expires_at);
"""

SEED_TYPES = [
    (1, "Asset"),
    (2, "Liability"),
    (3, "Income"),
    (4, "Expense"),
    (5, "Equity"),
]

SEED_SUBTYPES = [
    (1, "Current Asset", 1),
    (2, "Bank", 1),
    (3, "Investments", 1),
    (4, "Fixed Asset", 1),
    (5, "Current Liability", 2),
    (6, "Long-term Debt", 2),
    (7, "Salary", 3),
    (8, "Other Income", 3),
    (9, "Interest", 3),
    (10, "Dividends", 3),
    (11, "Automobile", 4),
    (12, "Groceries", 4),
    (13, "Housing", 4),
    (14, "Taxes", 4),
    (15, "Utilities", 4),
    (16, "Entertainment", 4),
    (17, "Current Expenses", 4),
    (18, "Net Worth", 5),
]

SEED_ACCOUNTS = [
    ("Cash", 1, 1, "Cash on hand", 0.0),
    ("Bank", 1, 2, "Main bank account", 0.0),
    ("Digital Wallet", 1, 2, "Digital wallet", 0.0),
    ("Credit Card", 2, 5, "Credit card", 0.0),
    ("Salary", 3, 7, "Salary income", 0.0),
    ("Other Income", 3, 8, "Miscellaneous income", 0.0),
    ("Groceries", 4, 12, "Supermarket and food", 0.0),
    ("Utilities", 4, 15, "Power, water, gas, internet", 0.0),
    ("Transport", 4, 11, "Fuel and transport", 0.0),
    ("Capital", 5, 18, "Personal equity", 0.0),
]


def table_exists(conn, table_name: str) -> bool:
    actual_name = _prefixed_table_name(table_name)
    row = conn.execute(
        """
        SELECT 1 AS exists_flag
        FROM information_schema.tables
        WHERE table_schema = current_schema() AND table_name = ?
        """,
        (actual_name,),
    ).fetchone()
    return bool(row)


def table_columns(conn, table_name: str) -> list[str]:
    actual_name = _prefixed_table_name(table_name)
    rows = conn.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = ?
        ORDER BY ordinal_position
        """,
        (actual_name,),
    ).fetchall()
    return [row["column_name"] for row in rows]


def _postgres_column_metadata(conn, table_name: str, column_name: str):
    return conn.execute(
        """
        SELECT is_identity, column_default
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = ?
          AND column_name = ?
        """,
        (_prefixed_table_name(table_name), column_name),
    ).fetchone()


def _postgres_column_uses_sequence(row) -> bool:
    if not row:
        return False
    if row["is_identity"] == "YES":
        return True
    default = row["column_default"] or ""
    return "nextval(" in default


def _ensure_postgres_identity_column(conn, table_name: str, column_name: str = "id"):
    row = _postgres_column_metadata(conn, table_name, column_name)
    if not row or _postgres_column_uses_sequence(row):
        return

    actual_name = _prefixed_table_name(table_name)
    conn.execute(
        f'ALTER TABLE "{actual_name}" ALTER COLUMN "{column_name}" '
        "ADD GENERATED BY DEFAULT AS IDENTITY"
    )


def _reset_postgres_sequence(conn, table_name: str, column_name: str = "id"):
    row = _postgres_column_metadata(conn, table_name, column_name)
    if not _postgres_column_uses_sequence(row):
        return

    actual_name = _prefixed_table_name(table_name)
    next_val = conn.execute(
        f'SELECT COALESCE(MAX("{column_name}"), 0) + 1 AS next_val '
        f'FROM "{actual_name}"'
    ).fetchone()["next_val"]
    conn.execute(
        f"SELECT setval(pg_get_serial_sequence('{actual_name}', '{column_name}'), ?, false)",
        (next_val,),
    )


def _ensure_projection_series_enabled_column(conn):
    actual_name = _prefixed_table_name("projection_series")
    conn.execute(
        f'ALTER TABLE "{actual_name}" ADD COLUMN IF NOT EXISTS enabled '
        "BOOLEAN NOT NULL DEFAULT TRUE"
    )


def _ensure_projection_series_period_months_column(conn):
    actual_name = _prefixed_table_name("projection_series")
    conn.execute(
        f'ALTER TABLE "{actual_name}" ADD COLUMN IF NOT EXISTS period_months '
        "INTEGER NOT NULL DEFAULT 1 CHECK(period_months >= 1)"
    )


def _ensure_projection_series_confirmed_column(conn):
    actual_name = _prefixed_table_name("projection_series")
    conn.execute(
        f'ALTER TABLE "{actual_name}" ADD COLUMN IF NOT EXISTS confirmed '
        "BOOLEAN NOT NULL DEFAULT FALSE"
    )


def _ensure_projection_series_type_check(conn):
    """Widen the CHECK constraint on projection_series.type to include investment/rescue."""
    actual_name = _prefixed_table_name("projection_series")
    conn.execute(
        f'ALTER TABLE "{actual_name}" DROP CONSTRAINT IF EXISTS projection_series_type_check'
    )
    conn.execute(
        f'ALTER TABLE "{actual_name}" DROP CONSTRAINT IF EXISTS oacc_projection_series_type_check'
    )
    conn.execute(
        f"""ALTER TABLE "{actual_name}" ADD CONSTRAINT {actual_name}_type_check
           CHECK (type IN ('income', 'expense', 'investment', 'rescue'))"""
    )


def init_db(get_db_func=None):
    db_factory = get_db_func or get_db
    with db_factory() as conn:
        conn.executescript(POSTGRES_SCHEMA)
        _ensure_postgres_identity_column(conn, "subtypes")
        _ensure_projection_series_enabled_column(conn)
        _ensure_projection_series_period_months_column(conn)
        _ensure_projection_series_confirmed_column(conn)
        _ensure_projection_series_type_check(conn)
        for type_id, type_name in SEED_TYPES:
            conn.execute(
                "INSERT INTO types (id, name) VALUES (?, ?) ON CONFLICT(id) DO NOTHING",
                (type_id, type_name),
            )
        for subtype_id, subtype_name, type_id in SEED_SUBTYPES:
            conn.execute(
                """
                INSERT INTO subtypes (id, name, type_id)
                VALUES (?, ?, ?)
                ON CONFLICT(id) DO NOTHING
                """,
                (subtype_id, subtype_name, type_id),
            )
        _reset_postgres_sequence(conn, "subtypes")

        count_row = conn.execute(
            "SELECT COUNT(*) AS account_count FROM accounts"
        ).fetchone()
        if int(count_row["account_count"]) == 0:
            for (
                name,
                type_id,
                subtype_id,
                description,
                initial_balance,
            ) in SEED_ACCOUNTS:
                conn.execute(
                    """
                    INSERT INTO accounts
                        (name, type_id, subtype_id, description, initial_balance)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (name, type_id, subtype_id, description, initial_balance),
                )
